name: Check if new version is available

on:
  workflow_dispatch:
  schedule:
    - cron: "25 0 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Get latest anki release
        run: echo "LATEST_VERSION=$(curl -s https://api.github.com/repos/ankitects/anki/releases/latest | jq -r '.tag_name')" >> $GITHUB_ENV

      - name: Check if GHCR image tag exists
        id: check
        run: |
          TOKEN=$(echo -n "${{ secrets.GITHUB_TOKEN }}" | base64)
          # HEAD request to manifest endpoint
          if curl --head --fail \
             -H "Authorization: Bearer ${TOKEN}" \
             https://ghcr.io/v2/itsnicecraft/ankisyncserver/manifests/${{ env.LATEST_VERSION }}; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Dispatch build.yml workflow if tag does not exist
        if: env.exists == 'false'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
            -d '{"ref":"main", "inputs": {"ANKI_VERSION": "${{ env.LATEST_VERSION }}"}}'
